apiVersion: v1
kind: Pod
metadata:
  name: sistema-noticias
  labels:
    app: sistema-noticias
spec:
  containers:
  - name: sistema-noticias-container
    image: aluracursos/sistema-noticias:1
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    envFrom: 
      - configMapRef:
          name: sistema-configmap
